### PR TITLE
increase delay if dyndns not set

### LINKED ISSUE #17: Increase add_peers delay to get dynds from dappmanager API
The current delay to get the dyndns from dappmanager API may not be enough and the endpoint may be empty so the credentials will not work
- [ ] Test average time dappmanager to get dynds when installing dappnode from scratch
- [x] Set proper time in https://github.com/dappnode/DNP_WIREGUARD/blob/master/root/etc/cont-init.d/30-config#L249

### PR DESCRIPTION
**Pull request by pablomendezroyo**
- Increase delay to get dyndns from 40 secs to 3 mins

### CODE REVIEW

**Review by 3alpha — APPROVED** [review]

File: root/etc/cont-init.d/30-config [hunk 1]
```diff
@@ -254,6 +254,10 @@ if [ -n "$PEERS" ]; then
   else
     echo "**** External server address is set to $SERVERURL ****"
   fi
+
+  # Exit if SERVERURL not set
+  [ -z "$SERVERURL" ] && { echo "**** ERROR: External server address not found at my.dappnode/global-envs/HOSTNAME ****"; exit 1}
```
Comment (3alpha) [inline root/etc/cont-init.d/30-config]: This is just init script, not sure that `exit 1` will kill whole container.

Comment (pablomendezroyo) [reply root/etc/cont-init.d/30-config]: Adding `set -e` and having the propert restart policy should be enough right?

Comment (3alpha) [reply root/etc/cont-init.d/30-config]: Because everything is run by https://github.com/just-containers/s6-overlay#customizing-s6-behaviour it seems that we need to set environment variable `S6_BEHAVIOUR_IF_STAGE2_FAILS `.

Comment (pablomendezroyo) [reply root/etc/cont-init.d/30-config]: nice catch! so what should we do to includ this?
- env `S6_BEHAVIOUR_IF_STAGE2_FAILS`  only in this script or in `docker-compose.yml`
- `set -e`
- exit 1
?

Comment (3alpha) [reply root/etc/cont-init.d/30-config]: I would set it in Dockerfile so UI isn't spammed with all kinds of env variables.

Comment (pablomendezroyo) [reply root/etc/cont-init.d/30-config]: exit on error would require more research for next release https://github.com/dappnode/DNP_WIREGUARD/issues/20
